name: sumangalam
description: A new Flutter project.
publish_to: none

version: '1.0.3+11'
environment: 
  sdk: '>=3.4.3 <4.0.0'

dependencies: 
  animated_custom_dropdown: '^3.1.1'
  connectivity_plus: ^6.1.0
  cupertino_icons: '^1.0.6'
  dartz: '^0.10.1'
  dio: ^5.7.0
  equatable: ^2.0.5
  file_picker: '^8.0.5'
  firebase_core: ^3.9.0
  firebase_crashlytics: '^4.0.1'
  flutter: 
    sdk: flutter
  flutter_barcode_scanner: ^2.0.0
  flutter_bloc: '^8.1.6'
  flutter_secure_storage: '^9.2.2'
  flutter_svg: '^2.0.10+1'
  freezed_annotation: '^2.4.1'
  geocoding: ^3.0.0
  geolocator: ^13.0.2
  get_it: '^7.6.7'
  go_router: '^14.1.4'
  google_fonts: '^6.2.1'
  google_generative_ai: ^0.4.6
  image_picker: '^1.1.2'
  injectable: '^2.4.2'
  injector: '^3.0.0'
  intl: '^0.19.0'
  logger: '^2.3.0'
  package_info_plus: ^8.1.1
  photo_view: '^0.15.0'
  shared_preferences: '^2.2.3'
  svg_flutter: '^0.0.1'
  tuple: ^2.0.2
  url_launcher: ^6.3.1

dev_dependencies: 
  build_runner: '^2.4.11'
  flutter_launcher_icons: ^0.13.1
  flutter_lints: '^3.0.0'
  flutter_test: 
    sdk: flutter

  freezed: '^2.5.2'
  injectable_generator: '^2.6.1'
  json_serializable: '^6.8.0'
  pubspec_dependency_sorter: '^1.0.4'
  
flutter: 
  uses-material-design: true
  assets: 
    - assets/images/

flutter_launcher_icons:
  android: 'launcher_icon'
  ios: true
  image_path: 'assets/images/app_icon.png'
  min_sdk_android: 21